version: '3.7'

services:
  api:
    container_name: api
    build: ./api
    ports:
      - 1234:1234
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "-t", "5", "--", "nodemon"]

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - 27017:27017